### ISSUE TITLE
Volume mesh generation of complex configurations

### ISSUE THREAD

**Issue by KW3303** [mdolab/pyhyp#10]
Can this tool be used to generate the volume mesh of the wing-body or wing-body-tail configurations automatically based on relative high quality surface mesh? If it works, How do I set the parameters？Thanks！

**Comment by johnjasa** [comment]
Hey there, pyHyp can indeed be used for those collar meshes. Do you already have the surface meshes for those?

I would suggest working through some pyHyp simple examples and playing with the parameters to get a feel for how they work. I've attached a script from 2 years that was used to extrude the surface mesh of an intersection to produce a volume mesh. I'm not sure if it would still work exactly, but you can see some of the parameters used. Again, all of these are case and mesh size dependent.

[script05_runPyhyp_py.txt](https://github.com/mdolab/pyhyp/files/3799054/script05_runPyhyp_py.txt)

**Comment by KW3303** [comment]
@johnjasa  Yes, I  have the surface grid of CRM wing-body-tail configuration already, and its quality is over 7. afterwords, I tried to modify the parameters refer to the script you've attached, but still failed. So, I generated a volume mesh immediately. Thank you.

**Comment by bhargavisrinivas666** [comment]
> @johnjasa Yes, I have the surface grid of CRM wing-body-tail configuration already, and its quality is over 7. afterwords, I tried to

I'm trying to generate volume mesh from a surface mesh of body-wing geometry,but I'm getting 
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node e040abf9c0f0 exited on signal 11 (Segmentation fault) error.What are the changes you have done in the script which lead to volume mesh generation successfully.Thanks in advance
