### ISSUE TITLE
Mismatched config filename in compilation step of installation instructions

### ISSUE THREAD

**Issue by galenng525** [mdolab/pyhyp#20]
## Filename 
What types of issue is it?

- Documentation update

## Description
In the instructions in this link: https://mdolab-pyhyp.readthedocs-hosted.com/en/latest/install.html, it says to copy a file named _config.LINUX_GFORTRAN.mk_ 
but the only files in the config/defaults/ are 
_config.LINUX_GFORTRAN_OPENMPI.mk_ 
and 
_config.LINUX_INTEL_OPENMPI.mk_
Is there supposed to be a file named 
_config.LINUX_GFORTRAN.mk_ 
in there or is this just a documentation update? I am unsure so I didn't want to submit a pull request.
### Steps to reproduce issue
1. …N/A
2. …
3. …

### Current behavior
…

### Expected behavior
…

### Code version (if relevant)
**Python version:** …

**External dependencies:** …

**Internal packages:** …

**Comment by nwu63** [comment]
Nope you are right, the documentation should be updated to match the config file name in the repo. Would you be able to do this at some point? There's no rush or anything.

**Comment by sseraj** [comment]
Fixed in #22
