### ISSUE TITLE
Naming BC in pyhyp

### ISSUE THREAD

**Issue by CODE-Lab-IASTATE** [mdolab/pyhyp#8]
I am currently running the 2D naca0012 tutorial in pyhyp. Everything works well. However, I need to specify names to the airfoil surface as well as the farfield domain in order to be able to specify boundary conditions to these surfaces in SU2. How do I do this?

**Comment by friedenhe** [comment]
Hi, pyHyp outputs multi-block cgns meshes. These meshes can not be directly used by SU2 because SU2 supports only single-block cgns meshes. You can use ICEM to load the pyHyp mesh, manually convert the multi-block format to the single-block one, and separate mesh surfaces & set names in ICEM.

**Comment by Jethro-Moses** [comment]
If I were to use the cgns file from pyHyp to OpenFOAM instead of SU2, do I still need to used ICEMCFD to names to patches? What would be the best way to do so?

**Comment by friedenhe** [comment]
@Jethro-Moses , In that case, you will need to output the mesh in plot3D format using pyHyp and convert it to OpenFOAM meshes using the OpenFOAM utilities. No need to use ICEM. You can refer to the Allrun.sh script in the NACA airfoil tutorial case in DAFoam.

**Comment by Jethro-Moses** [comment]
I got it to work, thanks a ton!
