### ISSUE TITLE
calculation y plus 

### ISSUE THREAD

**Issue by MachAeroDeveloper** [mdolab/pyhyp#97]
# Description of feature
can you give a way to calculate the yplus for the mesh of the generted file .cgns and give me the parameter that i can use it to calculate it it will be great help for me thank you

**Comment by A-CGray** [comment]
First cell y+ depends on the flow as well as the mesh spacing so it's not possible for pyhyp to give you a y+ value based on the mesh alone. The best approach is to use an [online calculator](https://www.cadence.com/en_US/home/tools/system-analysis/computational-fluid-dynamics/y-plus.html) to compute the first layer height that will give your desired y+ for your flow conditions and then use that value as input to pyhyp.
